### ISSUE TITLE
Hero Background Image?

### ISSUE THREAD

**Issue by mrworthington** [themefisher/navigator-hugo#1]
Hello! 

This theme looks amazing and has a ton of functionality. I was wondering if there was a way to add an image to hero background in order to have this kind of look: [example site](http://latondresse.org)

Thanks!

**Comment by mehedi-sharif** [comment]
Hello @mrworthington  ,
Yes its possible , its a css hack . https://www.w3schools.com/cssref/pr_background-image.asp Please check this .. 
Thanks

**Comment by mrworthington** [comment]
Hey! Thanks. So, I just tried adding the background image option to the .body css tag, but nothing showed. However, I also tried the .navigation and .hero-area tags and those did work, but only for the areas defined by each tag. 

Got any ideas for why the body area might not display the image while the other two do?

**Comment by mehedi-sharif** [comment]
open style.css file and in line number 563 there is a css class .hero-area . Remove the background color and add your background image css . It will work . :) If you can not do that make a donation my team will do that for you . 
Thanks
