### ISSUE TITLE
How to disable the form javascript/php sending part  

### ISSUE THREAD

**Issue by divinerites** [themefisher/navigator-hugo#12]
Hello,

I make the request here (may be it is better to do it on your themefisher web site as I paid the theme ? let me know) 

- I want to use the Netlify Form feature. They just need a regular form.
- I have a form working in an other theme which is **exactly** the same than the form in contact.html navigator.

But my navigator form do not work.

I looked at the code and there is a script.js who is doing :
- check if all fields are writen (this par tis OK)
- send the form via php => this is the cause of the form not working with Netlify.

But i can't find a way to disable the javascript/php part.
Any info / help / tip on how to properly disable the javascript php to have a regular form ??

Thnaks

**Comment by MarcinNaw** [comment]
Just delete the PHP part.

Netlify supports HTML forms, so php should be replaced by this. This is rather an netlify-issue I believe, check out their tutorial: [https://www.netlify.com/docs/form-handling/](https://www.netlify.com/docs/form-handling/)

**Comment by mehedi-sharif** [comment]
@divinerites Its better to reach me through my website or my email . 
Thanks
