### ISSUE TITLE
Video player play-icon is not centered vertically

### ISSUE THREAD

**Issue by MarcinNaw** [themefisher/navigator-hugo#13]
If you open the page full-screen and slowly reduce the width of the window, the video thumbnail and the play-icon do not respond the same way: The play button aligns at the bottom of the thumbnail at specific widths (100% reproducable).

Regards.

Edit: I just posted the content of this issue.

**Comment by mehedi-sharif** [comment]
We will fix this soon .Thanks for your concern .
