### ISSUE TITLE
Portfolio (Work Showcase) - Incosistent Behaviour on Mobile

### ISSUE THREAD

**Issue by MarcinNaw** [themefisher/navigator-hugo#14]
Clicking at one of the portfolio images leads to 3 different behaviours on mobile phones (tested on Safari@IOS and Chrome@Android):

1. The page reloads completely.
2. The pink overlay with the description appears.
3. The lightbox with the large image pops up.

As far as I can tell this is dependant on the position of the click.

1. Pink overlay appears, if we do not click on any _invisible_ element.
2. Page reloads, if the _invisible_ description is clicked.
3. Lightbox appears, if the _invisible_ search-icon is clicked.

I hope this helps to improve this great template.

**Comment by Somrat37** [comment]
Hey @MarcinNaw ,
thanks for inform us this issue, i just fixed this. now u can check it out.
