### ISSUE TITLE
How can I completely disable the multi-language feature?

### ISSUE THREAD

**Issue by patrickbolle** [themefisher/navigator-hugo#15]
Hi there, great theme. 
Trying to completely remove any reference to French or the multi-language feature. 

How can I do this best?

**Comment by divinerites** [comment]
I guess if you do not need multilanguage you just have to get to the lastest commit before the multilinguage feature.

**Comment by divinerites** [comment]
Or can just disable french 
https://gohugo.io/content-management/multilingual/#disable-a-language
