### ISSUE TITLE
error when deploying this theme

### ISSUE THREAD

**Issue by seethun** [themefisher/navigator-hugo#17]
I'm getting this error when running hugo server. I've followed the same steps as with other themes; for some reason, only this theme gives this error. Please help!

hugo server -b="http://test.s3-website-us-east-1.amazonaws.com/test/hugo/navigator-hugo" --renderToDisk --appendPort=false
ERROR Failed to read Git log: fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Total in 127 ms
Error: Error building site: logged 1 error(s)

**Comment by mehedi-sharif** [comment]
can you please update your hugo version .

**Comment by seethun** [comment]
Thanks Mehedi. That didn't help. I was running the latest version 0.54 and get the error mentioned

**Comment by Somrat37** [comment]
@seethun you need to initialize git. after a commit u can run hugo serve without any error.
