### ISSUE TITLE
404 for sections on hugo demo themes

### ISSUE THREAD

**Issue by divinerites** [themefisher/navigator-hugo#19]
On the demo website theme deployed by themes.gohugo.io, every section page is 404 (fr and en)

I had a quick (really quick) look but I see nothing obvious.
Put it here in case someone can have a look.

EDIT : Only portfolio and services has this problem. But seems like blog images have pb too.

**Comment by Somrat37** [comment]
hey @divinerites, thanks for your concern. this problem is only the hugo demo site. in localhost, there is no problem at all. you can download the theme and run it. it works absolutely fine.

**Comment by divinerites** [comment]
Yes I do know (i'm using it in production, even if I heavily modified it).

Just let you know because it doesn't deserve your great work.

**Comment by mehedi-sharif** [comment]
@divinerites  they have few issues with their demo page. Hope they will fix this issue soon . Its not a issue from our end. Let see how they handle this issue .

**Comment by divinerites** [comment]
Had a better look.

A - There is something strange on the [menu] section from /example/config.toml.

- You only have one menu without language.
```
[menu]
    [[menu.nav]]
    ...
```
- My multilingual version is using languaged version of menu.
```
[Languages]
   [Languages.fr]
      [Languages.fr.menu]
         [[Languages.fr.menu.nav]]
       ...
   [Languages.nl]
      [Languages.nl.menu]
         [[Languages.nl.menu.nav]]
```

B - Seems like you get an empty `.Param.image` on the /en/about page 

`<img src="{{ with .Params.image }}{{ . | absURL }}{{ end }}" class="w-100 mb-3" alt="Post-Image">
`

C - I also remember having to correct some trailing `/` problem with baseURL on 0.54

D - you also can update `.Site` for `site.`

HTH

**Comment by divinerites** [comment]
For finding all those problems (in particular those related to hugo behaviour changes) I use https://github.com/wjdp/htmltest on my public folder.

It show a lot of stuff related to hugo changes. And it is in my CI now.
