### ISSUE TITLE
How to use external icon packs?

### ISSUE THREAD

**Issue by chikity** [themefisher/navigator-hugo#20]
Hi!

Does this theme support using icons from other sources?  Say, fontawesome etc.?  If so how to get it to work?

Thanks

**Comment by Somrat37** [comment]
Hey @chikity ,
Sorry to say that we have no option to change icon pack in this template. But if you have a simple knowledge of coding then you can do it from changing some code from layouts. like (from header) you need to add icon pack link and where you want to change the icon, you need to change the icon class there.

**Comment by chikity** [comment]
Thanks for the reply @Somrat37 , I try it out.
