### ISSUE TITLE
List syntax in .md file not rendering

### ISSUE THREAD

**Issue by divyats6550** [themefisher/navigator-hugo#22]
I was trying to use the following syntax in my .md file, but when it renders in the site, bullet points are not showing.

What might be the issue? Is it like this theme wont support bullet points ?

Please help me out

syntax i used is :

 "*" added in the beginning of required lines

**Comment by divinerites** [comment]
You can try to add some css :

/* list in posts .md */
.blog-single ol li, .blog-single ul li {
  list-style-type: disc;
}
