### ISSUE TITLE
The git clone line in the instructions may need to be updated.

### ISSUE THREAD

**Issue by Dulani** [themefisher/navigator-hugo#28]
I tried the line in your installation instructions: 
`git clone git@github.com:themefisher/navigator-hugo.git`

And got the following result: 
```
Cloning into 'navigator-hugo'...
Warning: Permanently added the RSA host key for IP address '{redacted}' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
So, I used this instead which worked fine: 
`git clone https://github.com/themefisher/navigator-hugo.git`

**Comment by Somrat37** [comment]
Hey there, thanks for your concern. I will fix it.
