### ISSUE TITLE
Top menu turns white when "fixed" options is true in config

### ISSUE THREAD

**Issue by hrqmonteiro** [themefisher/navigator-hugo#32]
![2020 05 26-19 22 05 screenshot](https://user-images.githubusercontent.com/17055027/82956154-9441dd80-9f86-11ea-836e-fe18238ac4a1.png)

![2020 05 26-19 22 12 screenshot](https://user-images.githubusercontent.com/17055027/82956156-95730a80-9f86-11ea-9b04-60ab0c8b61af.png)

Help, when i set the "fixed" option for the top menu, it becames transparent and all buggy, any way that i can set a color for it when it is fixed? I tried everything i could on the css but wasn't able to do it..

**Comment by somrat-gyver** [comment]
Hey there, thanks for your concern. I have fixed this issue, please download the latest code.
