### ISSUE TITLE
Homepage 2 to Hugo?

### ISSUE THREAD

**Issue by stephenajulu** [themefisher/navigator-hugo#33]
@farcasmihai91 That demo page is for html version . Its not included in hugo.

_Originally posted by @mehedi-sharif in https://github.com/themefisher/navigator-hugo/issues/9#issuecomment-419695913_

Hi is there a way to add that to the hugo?

What i am reffering to: http://demo.themefisher.com/themefisher/navigator/index-2.html

**Comment by developer-evan** [comment]
hey there, we don't have any plan to add this page in the Hugo version. You can contact us at themefisher@gmail.com to customize or add some feature in your Hugo project. thanks.
