### ISSUE TITLE
Easy, New Install(like Megha with Git, Netlify and Forestry)

### ISSUE THREAD

**Issue by stephenajulu** [themefisher/navigator-hugo#34]
Hi, how are you?
Could you kindly add this easy install feature to this as well?

**Comment by developer-evan** [comment]
hey there, thanks for your concern, we will add this feature to all our template step by step. if you need it urgently then contact us at themefiser@gmail.com. thanks

**Comment by stephenajulu** [comment]
Hey, not yet?

**Comment by somratpro** [comment]
Hello @stephenajulu 

How are you? Actually, we have a lot of tasks to do, and we don't have much time. But the good news is, now we have a plan to update the old theme and added easy install to it. This theme is also included in the task. Hopefully, we will do it very soon. Stay connected with us.
