### ISSUE TITLE
How do i setup the contact form?

### ISSUE THREAD

**Issue by hrqmonteiro** [themefisher/navigator-hugo#35]
It's really just for showing or it does really work? I've search through all of it and there's nowhere i could find that i can set an e-mail and make it work.
Any help please?

**Comment by developer-evan** [comment]
hey there, you can use https://formspree.io form in this theme. for this, you need to create an account of formspree, then copy the form action and place it on config.toml file (contact_form_action field). action will look like "formspree.io/your.name@email.com"

also if you like our theme, then give a star. it will be amazing. thanks.
