### ISSUE TITLE
Error: failed to load translations

### ISSUE THREAD

**Issue by mcoshima** [themefisher/navigator-hugo#36]
I am trying to add new blog posts to my site but when I add one or edit an existing one I get the error 
Error: add site dependencies: load resources: loading translations: ".\Website-Navigator\i18n\en.toml:23:2": failed to load translations: (23, 2): duplicated tables .
What does this error mean and how do I fix it.
Thanks!

**Comment by developer-evan** [comment]
maybe you duplicated the translations in i18n/en.toml file. please check it.

**Comment by mcoshima** [comment]
Yes that fixed it thanks!
