### ISSUE TITLE
[Question] Disable preloader and have a static navbar

### ISSUE THREAD

**Issue by jxmesth** [themefisher/navigator-hugo#37]
I would appreciate it if someone could guide me through disabling the preloader and making the navbar static. Thank you for any help in advance :)

**Comment by developer-evan** [comment]
Hello @jxmesth 

You can remove the preloader form `layouts/_default/baseof.html`. Remove the line at 5 `{{ partial "preloader.html" . }}`

and what did you mean by making static navbar. I didn't understand. Did you want it sticky-top or something? please let me know...

**Comment by jxmesth** [comment]
Thank you for your reply. 

When I say "static navbar", what I mean is, is there a way to make the navbar not reload every time I refresh or go from one page to another. Basically, I want the body content to change when I switch pages with a navbar that doesn't reload. Thanks again for your help :)

**Comment by developer-evan** [comment]
@jxmesth 

I am sorry to say that, it is not possible in this theme, because every page generates from its main structure which has defined the navbar. so when you go to one page from another page, the navbar will be reloaded too. thank you.

**Comment by jxmesth** [comment]
Alright, thank you for your help :)
