### ISSUE TITLE
How do I add pages to the website?

### ISSUE THREAD

**Issue by jxmesth** [themefisher/navigator-hugo#38]
I would like to make the items on the 'Service' page links, For example, on the demo website's Service page, under 'Branding', I would like to make each item a link to another new page that would detail each service. i.e. Brand Strategy, Advertising / Campaigns, Product Design, etc would all be individual links to pages that would detail each service. How would I go about implementing this?

Any help would be greatly appreciated. Thanks.

**Comment by divinerites** [comment]
For this you need to understand how gohugo.io works.
You can look at making new page in Content and making a new corresponding template.
But this belongs to Hugo doc/forum and not the theme. See https://discourse.gohugo.io/

Or you may be you can rent themefisher to make this for you.

**Comment by jxmesth** [comment]
Thank you for your quick reply.  I'll take a look at it.
