### ISSUE TITLE
Considering make this theme multilingual ...

### ISSUE THREAD

**Issue by divinerites** [themefisher/navigator-hugo#4]
Hello @mehedi-sharif  I'm an happy Airspace user (the Cocoon tents)

I have a project (My daugther's camping proper web site) almost finished (using Prologue theme) and it is multilingual.

I really like your themes and may be Navigator can be used and adapted. But I **need to make it multilingual.**

Before going to work on that, do you have an opinion about the ability of this theme to be adapted for multilingual purpose (I guess you have thought about that) or if ot will be too much work because of his architecture..

If my daughter agree on your design (I'm waiting on her response) I am ready to work for making it multilingual.

Any thought on that could help me deciding.
Anyway you have KILLER themes.
Regards.

**Comment by divinerites** [comment]
Is sound really promising. I just put the basics mecanism & adaptation for:

- translation for data/foo.yml
- translation for menu + flags select language.
- adaptation for some images URLs.

Blog content will be almost outofthebox Hugo behaviour i think.

**Comment by mehedi-sharif** [comment]
Hello @divinerites 
Thanks for your nice words . We made almost 5themes for hugo and they got very popular in hugo community . As we are running a team if this project is not successful we could not invest our time to make themes for hugo . We thought as hugo is a popular platform hope we can get some cream from here to survive my team . But the result is zero. So we stopped working on hugo and we no longer give support for this themes in this hugo platform . As I mentioned you before we are not going to give any commit in our hugo repositories so I would recommend you to choose other theme which has multilanguage support . Again thanks for your nice words . This kind of words inspire us a lot. 
Thanks

**Comment by divinerites** [comment]
I understand. No wories.
I'll make a PR when i have cleaned my multi-lingual modifications, so you can reuse it if needed.

**Comment by divinerites** [comment]
I looked at your website. I didn't saw Hugo premium theme to buy.
How can I support/buy premium this Navigator-hugo theme ?

**Comment by mehedi-sharif** [comment]
Hello @divinerites ,
There is no premium version of this template . I have added a paypal in the description where anyone pay donate any amount if that want :) 
https://github.com/themefisher/navigator-hugo 
Thanks for your contribution .

**Comment by divinerites** [comment]
Ah ok.

But if i buy the premium Navigator on your site, do i get a small support on the CSS/HTML side ?
I do not need "hugo support" on this theme just eventually some small css things I guess.

Or this hugo theme is very different from the one on your site ?
Sorry to insist, but i'm ready to buy it if i know i'll get small support :-)

And i'll still contribute for what I improve

**Comment by mehedi-sharif** [comment]
You will get support from us if you purchase the pro version :) Any kind of html css support :) 
Thanks

**Comment by divinerites** [comment]
Hello @mehedi-sharif, i finished to adapt your theme to multilingual (content, menus, yml, ...) and fixed dome small typos.

I do know that you will not invest time in this Hugo theme, but as I already made the work for this theme being natively multilingual, what is the best way to publish my work for others ? 
Do you have a wish  : I send you a zip ? I try to make a PR ?

I'll know do the proper work for adapting this theme to our needs. 
Regards.

PS : i purchased the original theme on you web site as a support for your great work.

**Comment by mehedi-sharif** [comment]
Hello @divinerites  ,
Just merged your push to the main branch.Thanks for your contribution . And yes I saw that you have purchased the pro version. A big love from my team.
Thanks
