### ISSUE TITLE
Linkable parent for nav-item with children

### ISSUE THREAD

**Issue by patrickderitter** [themefisher/navigator-hugo#40]
Thanks for the theme, great stuff! My nav-menu has one item with children, so that it becomes a dropdown menu. How can I make sure that the parent (so the toplevel item) can also link to a page?

**Comment by developer-evan** [comment]
Hello @patrickderitter ,

We are sorry to say that it is not possible, we used bootstrap for building this theme, and bootstrap does not support this facility.

**Comment by patrickderitter** [comment]
Okay, too bad but thanks!
