### ISSUE TITLE
OnClick works only once for Philosophy.yml Elements (Our Philosophy | Mission | Vision)

### ISSUE THREAD

**Issue by MarcinNaw** [themefisher/navigator-hugo#8]
Hey guys,

The selection points created in philosophy.yml (Our Philosophy | Mission | Vision) are only clickable once, afterwards nothing happens. 

Regards
  Marcin

(We are currently developing a homepage based on this theme for our sports club and already supported you with a donation. :)

**Comment by mehedi-sharif** [comment]
Hello Marcin,
Thanks for using our template and your support. Yes a javascript bug and we are going to solve this issue soon.

**Comment by divinerites** [comment]
I received a message that it is fixed in the themefisher theme to download.
I quickly looked at the source, and the only thing I see is the Bootstrap & JQuery version update.

Is this the only thing we have to change in the hugo port ?

**Comment by mehedi-sharif** [comment]
I am not sure is it fixed in hugo version or not. I am going to recheck this issue tomorrow.
Thanks

**Comment by MarcinNaw** [comment]
> I received a message that it is fixed in the themefisher theme to download.
> I quickly looked at the source, and the only thing I see is the Bootstrap & JQuery version update.
> 
> Is this the only thing we have to change in the hugo port ?

@kausarpial Any updates on this bug? 

@divinerites Was the bootstrap and jqery update helpful?

**Comment by kausarpial** [comment]
Was a little javascript error. 
Fixed With the current Update.
Thanks
