### ISSUE TITLE
Home page #2

### ISSUE THREAD

**Issue by farcasmihai91** [themefisher/navigator-hugo#9]
Hello,
On your demo page you have an url for Homepage 2 but I can't figure out how to switch from one to another.

Is this possible or is it not included in this version?

Thanks!

**Comment by farcasmihai91** [comment]
Sorry, no I did not mean multilingual, this demo page has a different page called index-2.html:
http://demo.themefisher.com/themefisher/navigator/index-2.html

Thanks again!

**Comment by mehedi-sharif** [comment]
@farcasmihai91 That demo page is for html version . Its not included in hugo.

**Comment by farcasmihai91** [comment]
Thank you!

**Comment by stephenajulu** [comment]
Hi, is there a way to add that to the hugo version?
